# Generated by Django 4.2.15 on 2024-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_exercise_workout_exercise_type_exercise_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
