# Generated by Django 4.2.15 on 2024-08-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_set_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sets', to='workouts.workout'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='workouts.exercise'),
        ),
    ]
